packages:
  - package/*

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  electron: true
  electron-winstaller: true
  esbuild: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - electron-winstaller
  - esbuild
